name: Deploy NoteApp BE

on:
  push:
    branches: [ main ]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: SERVER_APP

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /var/www/html/noteAppBe || https://github.com/buidaoanhvan/noteAppBe.git
          cd /var/www/html/noteAppBe
          git pull origin main
          npm install
          npm run build  # nếu có
          pm2 restart note-app || pm2 start app.js --name note-app
